package com.nekolr.saber.service;

import java.io.IOException;
import java.io.InputStream;

/**
 * All storage service should implement this interface
 */
public interface StorageService {

    /**
     * Upload file
     *
     * @param in          file inputStream
     * @param filename    origin name
     * @param contentType contentType
     * @param length      file length
     * @return A relative url str generated by storage service
     */
    String upload(InputStream in, String filename, String contentType, long length) throws IOException;

    /**
     * Delete file
     */
    void delete(String filename);
}
